# Generated by Django 2.1.2 on 2019-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190306_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='work_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
