# Generated by Django 2.1.2 on 2019-03-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190307_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='格式化秒',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
